// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paternoster.DAL;

#nullable disable

namespace Paternoster.Migrations
{
    [DbContext(typeof(PaternosterDbContext))]
    partial class PaternosterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Paternoster.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Paternoster.Models.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("Paternoster.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .IsUnique();

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Paternoster.Models.Paternoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFull")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfContainers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaternosterCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaternosterSystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaternosterSystemId");

                    b.ToTable("Paternosters");
                });

            modelBuilder.Entity("Paternoster.Models.PaternosterContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaternosterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaternosterId");

                    b.ToTable("PaternosterContainers");
                });

            modelBuilder.Entity("Paternoster.Models.PaternosterSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaternosterSystems");
                });

            modelBuilder.Entity("Paternoster.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Paternoster.Models.ProductPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductParts");
                });

            modelBuilder.Entity("Paternoster.Models.OrderLine", b =>
                {
                    b.HasOne("Paternoster.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paternoster.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Paternoster.Models.Part", b =>
                {
                    b.HasOne("Paternoster.Models.PaternosterContainer", "Container")
                        .WithOne("Part")
                        .HasForeignKey("Paternoster.Models.Part", "ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Paternoster.Models.Paternoster", b =>
                {
                    b.HasOne("Paternoster.Models.PaternosterSystem", "PaternosterSystem")
                        .WithMany("Paternosters")
                        .HasForeignKey("PaternosterSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaternosterSystem");
                });

            modelBuilder.Entity("Paternoster.Models.PaternosterContainer", b =>
                {
                    b.HasOne("Paternoster.Models.Paternoster", "Paternoster")
                        .WithMany("Containers")
                        .HasForeignKey("PaternosterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paternoster");
                });

            modelBuilder.Entity("Paternoster.Models.ProductPart", b =>
                {
                    b.HasOne("Paternoster.Models.Part", "Part")
                        .WithMany("Products")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paternoster.Models.Product", "Product")
                        .WithMany("ProductParts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Paternoster.Models.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("Paternoster.Models.Part", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Paternoster.Models.Paternoster", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("Paternoster.Models.PaternosterContainer", b =>
                {
                    b.Navigation("Part");
                });

            modelBuilder.Entity("Paternoster.Models.PaternosterSystem", b =>
                {
                    b.Navigation("Paternosters");
                });

            modelBuilder.Entity("Paternoster.Models.Product", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductParts");
                });
#pragma warning restore 612, 618
        }
    }
}
